# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fancygrid}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Gr\303\244fenstein"]
  s.date = %q{2010-10-20}
  s.description = %q{Easy tables in rails}
  s.email = %q{giniedp@online.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/public/images/fancygrid/add.png",
     "app/public/images/fancygrid/clear.png",
     "app/public/images/fancygrid/ddn.png",
     "app/public/images/fancygrid/dn.png",
     "app/public/images/fancygrid/first.png",
     "app/public/images/fancygrid/last.png",
     "app/public/images/fancygrid/loading.gif",
     "app/public/images/fancygrid/magnifier.png",
     "app/public/images/fancygrid/next.png",
     "app/public/images/fancygrid/prev.png",
     "app/public/images/fancygrid/reload.png",
     "app/public/images/fancygrid/th_bg.png",
     "app/public/images/fancygrid/up.png",
     "app/public/images/fancygrid/uup.png",
     "app/public/javascripts/fancygrid.js",
     "app/public/stylesheets/_fancygrid.scss",
     "app/public/stylesheets/fancygrid.css",
     "app/views/fancygrid/_cells.html.haml",
     "app/views/fancygrid/_controls.html.haml",
     "app/views/fancygrid/_frame.html.haml",
     "config/locales/fancygrid.de.yml",
     "config/locales/fancygrid.en.yml",
     "fancygrid.gemspec",
     "lib/fancygrid.rb",
     "lib/field.rb",
     "lib/field_helper.rb",
     "lib/grid.rb",
     "lib/grid_helper.rb",
     "lib/result.rb",
     "lib/tasks/fancygrid.rake",
     "lib/version.rb",
     "test/helper.rb",
     "test/test_fancygrid.rb"
  ]
  s.homepage = %q{http://github.com/giniedp/fancygrid}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Grids in rails}
  s.test_files = [
    "test/helper.rb",
     "test/test_fancygrid.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

