# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{railsgrid}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Gr\303\244fenstein"]
  s.date = %q{2010-10-18}
  s.description = %q{Easy tables in rails}
  s.email = %q{giniedp@online.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/public/images/railsgrid/add.png",
     "app/public/images/railsgrid/clear.png",
     "app/public/images/railsgrid/ddn.png",
     "app/public/images/railsgrid/dn.png",
     "app/public/images/railsgrid/first.png",
     "app/public/images/railsgrid/last.png",
     "app/public/images/railsgrid/loading.gif",
     "app/public/images/railsgrid/magnifier.png",
     "app/public/images/railsgrid/next.png",
     "app/public/images/railsgrid/prev.png",
     "app/public/images/railsgrid/reload.png",
     "app/public/images/railsgrid/th_bg.png",
     "app/public/images/railsgrid/up.png",
     "app/public/images/railsgrid/uup.png",
     "app/public/javascripts/railsgrid.js",
     "app/public/stylesheets/railsgrid.css",
     "app/views/railsgrid/_cells.html.haml",
     "app/views/railsgrid/_controls.html.haml",
     "app/views/railsgrid/_frame.html.haml",
     "config/locales/railsgrid.de.yml",
     "config/locales/railsgrid.en.yml",
     "lib/column.rb",
     "lib/railsgrid.rb",
     "lib/result.rb",
     "lib/table.rb",
     "lib/table_helper.rb",
     "lib/tasks/railsgrid.rake",
     "lib/version.rb",
     "railsgrid.gemspec",
     "test/helper.rb",
     "test/test_railsgrid.rb"
  ]
  s.homepage = %q{http://github.com/giniedp/railsgrid}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Tables in rails}
  s.test_files = [
    "test/helper.rb",
     "test/test_railsgrid.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

